### ISSUE TITLE
BlogPostIssue - GitHub Report Issue Button Post is missing an image

### ISSUE THREAD

**Issue by 1RedOne** [1RedOne/1redone.github.io#21]
Missing an image at the start of the post.  

---
Document Details

- Content  [GitHub Report Issue Button](https://1redone.github.io//blog/github-report-issue-button.html)
- Content Source  [_posts/2021-03-15-github-report-issue-button.md](https://github.com/1RedOne/1RedOne.Github.io/blob/master/_posts/2021-03-15-github-report-issue-button.md)

**Comment by robdy** [comment]
Cool idea, I recently added edit button to my posts and I guess that one will be next ;)

**Comment by 1RedOne** [comment]
Neat, I'm happy you liked it!  You can actually peek at my closed issues here if you want a window into how I work, as I was using the button to remind myself to fix issues in posts as I was reviewing them :)

**Comment by robdy** [comment]
I saw it. I do the same: https://github.com/robdy/robdy.github.io/issues 
One difference - in my case comments have dedicated repo so they don't mess with my notes
